name: Preprocess Workflow

on:
  push:
    paths:
      - 'automate_Akas.py'
      - '.workflow/preprocess.yml'

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install Dependencies
      run: pip install pandas scikit-learn

    - name: Run automate_Akas.py
      run: python automate_Akas.py
