name: Retrain ML Model

on:
  push:
    paths:
      - 'Workflow-CI/MLProject/**'
      - 'Workflow-CI/.github/workflows/retrain.yml'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: online-shop-env
        environment-file: Workflow-CI/MLProject/conda.yaml
        auto-activate-base: false

    - name: Install MLflow
      run: |
        pip install mlflow
        
    - name: Set MLflow Tracking URI to DagsHub
      run: |
        export MLFLOW_TRACKING_URI=https://dagshub.com/AkasSakti/Eksperimen_SML_Akas-Bagus-Setiawan/.mlflow
        export MLFLOW_TRACKING_USERNAME=<AkasSakti>
        export MLFLOW_TRACKING_PASSWORD=<77f65784ff8c1be54c8346460e9e9bf170d231db>

    - name: Run MLflow Project
      run: |
        cd Workflow-CI/MLProject
        mlflow run . --env-manager=local
