name: Train Model CI

on:
  push:
    paths:
      - "Workflow-CI/MLProject/**"

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: Workflow-CI/MLProject/conda.yaml
          activate-environment: ml-ci-env
      - name: Install MLflow
        run: pip install mlflow
      - name: Run MLflow Project
        run: mlflow run Workflow-CI/MLProject -P data=Workflow-CI/MLProject/olshopdatapreprocesed/preprocessed.csv
