# .github/workflows/train_model.yml
name: Train Model

on:
  push:
    paths:
      - 'Membangun_model/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r Membangun_model/requirements.txt

      - name: Run training script
        run: |
          python Membangun_model/modelling.py
